### ISSUE TITLE
strange content assist

### ISSUE THREAD

**Issue by michelpa** [pdt-eg/Core-Plugin#112]
Hello,

After updating, autocomplete add a backslash before all build-in function from "standard.php". Any clue on how to solve this?

Thanks.

Pascal

**Comment by zulus** [comment]
This is correct behaviour in current PDT-nightly if you are inside namespace, for performance reasons.

PHP (and PDT) search first for $namespace/func_name (for example in_array), next for \func_name. Since PHP 5.6 this problem grow up, because is possible to import and set alias to function.

See also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=448500

**Comment by michelpa** [comment]
OK, thanks for the clarification!

**Comment by michelpa** [comment]
OK, thanks for the clarification!

**Comment by michelpa** [comment]
OK, thanks for the clarification!

**Comment by zulus** [comment]
Just for notification, in current PDT-nightly, this behavior is disabled by default (you can enable it in preferences) ;)

**Comment by michelpa** [comment]
Thank you!
